In [1]:
# Import dependencies
import pandas as pd
import numpy as np

In [2]:
# Read in fight_data2010-2021 csv
historic_data = pd.read_csv("resources/fight_data2010-2021.csv")

# Only obtain relevant columns
fighter_data = historic_data.copy()

fighter_data = fighter_data.drop(
    ["R_odds", 
    "B_odds", 
    "R_ev", 
    "B_ev", 
    "location", 
    "country", 
    "title_bout", 
    "weight_class", 
    "gender", 
    "no_of_rounds", 
    "B_Weight_lbs", 
    "R_Weight_lbs", 
    "lose_streak_dif", 
    "win_streak_dif", 
    "longest_win_streak_dif",
    "win_dif",
    "loss_dif",
    "total_round_dif",
    "total_title_bout_dif",
    "ko_dif",
    "sub_dif",
    "height_dif",
    "reach_dif",
    "age_dif",
    "sig_str_dif",
    "avg_sub_att_dif",
    "avg_td_dif",
    "empty_arena",
    "constant_1",
    "B_match_weightclass_rank",
    "R_match_weightclass_rank",
    "R_Women's Flyweight_rank",
    "R_Women's Featherweight_rank",
    "R_Women's Strawweight_rank",
    "R_Women's Bantamweight_rank",
    "R_Heavyweight_rank",
    "R_Light Heavyweight_rank",
    "R_Middleweight_rank",
    "R_Welterweight_rank",
    "R_Lightweight_rank",
    "R_Featherweight_rank",
    "R_Bantamweight_rank",
    "R_Flyweight_rank",
    "R_Pound-for-Pound_rank",
    "B_Women's Flyweight_rank",
    "B_Women's Featherweight_rank",
    "B_Women's Strawweight_rank",
    "B_Women's Bantamweight_rank",
    "B_Heavyweight_rank",
    "B_Light Heavyweight_rank",
    "B_Middleweight_rank",
    "B_Welterweight_rank",
    "B_Lightweight_rank",
    "B_Featherweight_rank",
    "B_Bantamweight_rank",
    "B_Flyweight_rank",
    "B_Pound-for-Pound_rank",
    "better_rank",
    "finish",
    "finish_details",
    "finish_round",
    "finish_round_time",
    "total_fight_time_secs",
    "r_dec_odds",
    "b_dec_odds",
    "r_sub_odds",
    "b_sub_odds",
    "r_ko_odds",
    "b_ko_odds"
    ], axis = 1)

# Clean inconsistent dates in date columns
fighter_data["date"] = pd.to_datetime(fighter_data["date"])

# Remove NaNs
fighter_data = fighter_data.dropna()

# View dataframe
fighter_data

,R_fighter,B_fighter,date,Winner,B_current_lose_streak,B_current_win_streak,B_draw,B_avg_SIG_STR_landed,B_avg_SIG_STR_pct,B_avg_SUB_ATT,...,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_wins,R_Stance,R_Height_cms,R_Reach_cms,R_age,B_age
0,Thiago Santos,Johnny Walker,2021-10-02,Red,0,1,0,3.420000,0.5900,0.700000,...,2,11,0,0,13,Orthodox,187.96,193.04,37,29
1,Alex Oliveira,Niko Price,2021-10-02,Blue,2,0,0,5.160000,0.4200,0.800000,...,3,4,3,0,11,Orthodox,180.34,193.04,33,32
2,Misha Cirkunov,Krzysztof Jotko,2021-10-02,Blue,1,0,0,2.920000,0.4100,0.100000,...,0,1,5,0,6,Orthodox,190.50,195.58,34,32
3,Alexander Hernandez,Mike Breeden,2021-10-02,Red,1,0,0,4.040000,0.3400,0.000000,...,2,2,0,0,4,Orthodox,175.26,182.88,29,32
4,Joe Solecki,Jared Gordon,2021-10-02,Blue,0,2,0,5.220000,0.5600,0.000000,...,2,0,2,0,4,Orthodox,175.26,177.80,28,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4888,Alessio Sakara,James Irvin,2010-03-21,Red,1,0,0,5.250000,0.5550,0.125000,...,1,3,0,0,5,Orthodox,182.88,182.88,28,31
4889,Clay Guida,Shannon Gugerty,2010-03-21,Red,1,0,0,10.750000,0.3325,1.250000,...,1,1,1,0,5,Orthodox,170.18,177.80,28,28
4890,Eliot Marshall,Vladimir Matyushenko,2010-03-21,Blue,0,1,0,22.166667,0.5100,0.166667,...,1,0,1,0,3,Orthodox,187.96,195.58,29,39
4893,Brendan Schaub,Chase Gormley,2010-03-21,Red,1,0,0,8.000000,0.3400,1.000000,...,0,0,0,0,0,Orthodox,193.04,198.12,27,27
4895,Eric Schafer,Jason Brilz,2010-03-21,Blue,1,0,0,31.666667,0.4600,0.666667,...,0,1,2,0,3,Orthodox,190.50,190.50,32,34

Create dataframe for use in ML fight predictor model

In [3]:
# Create dataframe to use in fight predictor model
predict_data = fighter_data.copy()

# Drop any irrelevant columns
predict_data = predict_data.drop(
    ["R_fighter",
    "B_fighter",
    "date"], axis = 1)

# Display df
predict_data

# Store data as csv
predict_data.to_csv("resources/predict_data.csv")

Create dataframe for use in UFC fighter map, charts and ML user input

In [4]:
# Read in fighter_data csv and obtain relevant columns
location_data = pd.read_csv("resources/fighter_data.csv")
fighter_location_b = location_data[["B_Name", "B_Location"]].rename(columns = {"B_Name":"name", "B_Location": "location"})
fighter_location_r = location_data[["R_Name", "R_Location"]].rename(columns = {"R_Name":"name", "R_Location": "location"})
fighter_location = pd.concat([fighter_location_b,fighter_location_r])
fighter_location = fighter_location.groupby("name").last()
fighter_location

                                                    location
name
Aaron Phillips                             Lafayette, LA USA
Abdul Razak Alhassan         Fort Worth, Texas United States
Abel Trujillo              Boca Raton, Florida United States
Abner Lloveras                               Barcelona Spain
Adam Milstead         Pittsburgh, Pennsylvania United States
...                                                      ...
Zach Makovsky                 Philadelphia, Pennsylvania USA
Zak Cummings                             Kansas City, MO USA
Zak Ottow                 Milwuakee, Wisconsin United States
Zhang Lipeng                                   Beijing China
Zubaira Tukhugov             Grozny, Chechen Republic Russia

[852 rows x 1 columns]

In [7]:
# Create dataframes for each red and blue fighter

# Create lists of columns in dataframe

B_column_list = ["B_fighter", 
                "date",
                "B_wins",
                "B_losses",
                "B_draw",
                "B_current_lose_streak",
                "B_current_win_streak",
                "B_avg_SIG_STR_landed",
                "B_avg_SIG_STR_pct",
                "B_avg_SUB_ATT",
                "B_avg_TD_landed",
                "B_avg_TD_pct",
                "B_longest_win_streak",
                "B_total_rounds_fought",
                "B_total_title_bouts",
                "B_win_by_Decision_Majority",
                "B_win_by_Decision_Split",
                "B_win_by_Decision_Unanimous",
                "B_win_by_KO/TKO",
                "B_win_by_Submission",
                "B_win_by_TKO_Doctor_Stoppage",
                "B_age",
                "B_Stance",
                "B_Height_cms",
                "B_Reach_cms"
                ]

R_column_list = ["R_fighter",
                "date",
                "R_wins",
                "R_losses",
                "R_draw",
                "R_current_lose_streak",
                "R_current_win_streak",
                "R_avg_SIG_STR_landed",
                "R_avg_SIG_STR_pct",
                "R_avg_SUB_ATT",
                "R_avg_TD_landed",
                "R_avg_TD_pct",
                "R_longest_win_streak",
                "R_total_rounds_fought",
                "R_total_title_bouts",
                "R_win_by_Decision_Majority",
                "R_win_by_Decision_Split",
                "R_win_by_Decision_Unanimous",
                "R_win_by_KO/TKO",
                "R_win_by_Submission",
                "R_win_by_TKO_Doctor_Stoppage",
                "R_age",
                "R_Stance",
                "R_Height_cms",
                "R_Reach_cms"
                ]

# Create list of columns for new dataframe
new_column_list = ["name",
                "date",
                "wins",
                "losses",
                "draw",
                "current_lose_streak",
                "current_win_streak",
                "avg_SIG_STR_landed",
                "avg_SIG_STR_pct",
                "avg_SUB_ATT",
                "avg_TD_landed",
                "avg_TD_pct",
                "longest_win_streak",
                "total_rounds_fought",
                "total_title_bouts",
                "win_by_Decision_Majority",
                "win_by_Decision_Split",
                "win_by_Decision_Unanimous",
                "win_by_KO/TKO",
                "win_by_Submission",
                "win_by_TKO_DoctoStoppage",
                "age",
                "Stance",
                "Height_cms",
                "Reach_cms"
                ]


# Create dictionaries to use for cleaning dataframe
R_col_replace = {}
B_col_replace = {}
R_count = 0
B_count = 0

for header in R_column_list:
    R_col_replace[header] = new_column_list[R_count]
    R_count +=1

for header in B_column_list:
    B_col_replace[header] = new_column_list[B_count]
    B_count +=1

In [8]:
# Create new dataframe
r_fighters = fighter_data[R_column_list]
b_fighters = fighter_data[B_column_list]
r_fighters = r_fighters.rename(columns = R_col_replace)
b_fighters = b_fighters.rename(columns = B_col_replace)
full_fighter_data = pd.concat([r_fighters,b_fighters])
full_fighter_data = full_fighter_data.sort_values("date").groupby("name").last()

# Create win ratio column
full_fighter_data["winratio"] = full_fighter_data["wins"]/(full_fighter_data["wins"]+full_fighter_data["losses"]+full_fighter_data["draw"])

# Display new dataframe
full_fighter_data

,date,wins,losses,draw,current_lose_streak,current_win_streak,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_landed,...,win_by_Decision_Split,win_by_Decision_Unanimous,win_by_KO/TKO,win_by_Submission,win_by_TKO_DoctoStoppage,age,Stance,Height_cms,Reach_cms,winratio
name,,,,,,,,,,,,,,,,,,,,,
Aalon Cruz,2021-03-06,1,1,0,1,0,7.58,0.39000,0.000,0.00,...,0,0,1,0,0,31,Switch,182.88,198.12,0.500000
Aaron Phillips,2020-07-15,0,2,0,2,0,1.87,0.59000,0.500,0.00,...,0,0,0,0,0,30,Southpaw,175.26,177.80,0.000000
Aaron Riley,2013-07-27,3,5,0,1,0,36.00,0.36875,0.125,1.00,...,0,3,0,0,0,32,Southpaw,172.72,175.26,0.375000
Aaron Rosa,2012-03-02,1,1,0,0,1,66.00,0.49500,0.000,0.00,...,0,0,0,0,0,28,Orthodox,193.04,198.12,0.500000
Aaron Simpson,2012-10-05,7,3,0,0,1,42.60,0.55000,0.300,3.10,...,1,4,2,0,0,38,Orthodox,182.88,185.42,0.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zhalgas Zhamagulov,2020-07-11,0,0,0,0,0,0.00,0.00000,0.000,0.00,...,0,0,0,0,0,31,Switch,162.56,162.56,NaN
Zhalgas Zhumagulov,2021-07-10,0,2,0,2,0,4.21,0.49000,0.500,1.40,...,0,0,0,0,0,32,Switch,162.56,167.64,0.000000
Zhang Lipeng,2015-05-16,2,1,0,1,0,19.00,0.49000,1.000,2.00,...,1,1,0,0,0,25,Southpaw,180.34,180.34,0.666667
Zhang Weili,2021-04-24,5,0,0,0,5,6.36,0.45000,0.500,1.24,...,1,2,1,1,0,31,Switch,162.56,160.02,1.000000
Zubaira Tukhugov,2020-09-26,4,1,1,0,1,2.58,0.38000,0.000,2.88,...,1,1,2,0,0,29,Orthodox,172.72,172.72,0.666667

In [9]:
# Save full_fighter_data as csv
full_fighter_data.to_csv("resources/goat_data.csv")

Create data for map visualisation

In [10]:
# Join fighter_location and fighter_data on full name
map_data = full_fighter_data.join(fighter_location, how = "inner")
map_data

# Note that dataframe has been reduced to 838 rows from 1749. This is because the location data is from 2014-2017, therefore it doesn't contain 
# any new fighters from 2018 to the present.

,date,wins,losses,draw,current_lose_streak,current_win_streak,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_landed,...,win_by_Decision_Unanimous,win_by_KO/TKO,win_by_Submission,win_by_TKO_DoctoStoppage,age,Stance,Height_cms,Reach_cms,winratio,location
name,,,,,,,,,,,,,,,,,,,,,
Aaron Phillips,2020-07-15,0,2,0,2,0,1.870000,0.590000,0.500000,0.000000,...,0,0,0,0,30,Southpaw,175.26,177.80,0.000000,"Lafayette, LA USA"
Abdul Razak Alhassan,2021-08-28,4,4,0,3,0,3.710000,0.480000,0.000000,0.530000,...,0,4,0,0,36,Orthodox,177.80,185.42,0.500000,"Fort Worth, Texas United States"
Abel Trujillo,2017-12-16,6,4,0,1,0,24.400000,0.372000,0.300000,1.400000,...,1,3,1,0,34,Orthodox,172.72,177.80,0.600000,"Boca Raton, Florida United States"
Adam Milstead,2018-12-15,1,2,0,2,0,39.000000,0.643333,0.000000,0.000000,...,0,1,0,0,31,Orthodox,190.50,193.04,0.333333,"Pittsburgh, Pennsylvania United States"
Adriano Martins,2017-09-09,4,2,0,1,0,14.500000,0.443333,0.166667,0.666667,...,0,2,1,0,34,Southpaw,177.80,182.88,0.666667,"Manaus, Amazonas Brazil"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zach Makovsky,2016-12-10,3,3,0,2,0,30.500000,0.443333,0.166667,3.666667,...,3,0,0,0,33,Southpaw,162.56,162.56,0.500000,"Philadelphia, Pennsylvania USA"
Zak Cummings,2020-08-29,8,5,0,1,0,2.470000,0.320000,0.800000,0.750000,...,3,1,4,0,36,Southpaw,182.88,190.50,0.615385,"Kansas City, MO USA"
Zak Ottow,2019-03-09,4,3,0,0,1,27.571429,0.358571,0.285714,0.571429,...,0,1,0,0,32,Orthodox,180.34,182.88,0.571429,"Milwuakee, Wisconsin United States"
Zhang Lipeng,2015-05-16,2,1,0,1,0,19.000000,0.490000,1.000000,2.000000,...,1,0,0,0,25,Southpaw,180.34,180.34,0.666667,Beijing China
Zubaira Tukhugov,2020-09-26,4,1,1,0,1,2.580000,0.380000,0.000000,2.880000,...,1,2,0,0,29,Orthodox,172.72,172.72,0.666667,"Grozny, Chechen Republic Russia"

In [11]:
# Save data to create map as csv
map_data.to_csv("resources/map_data.csv")

In [12]:
# Load data to database 

# SQL Alchemy
from sqlalchemy import create_engine

fight_database_path = "resources/fighter_data.sqlite"
engine = create_engine(f"sqlite:///{fight_database_path}")
conn = engine.connect()

map_data.to_sql("map_data", conn, if_exists = "replace")
full_fighter_data.to_sql("goat_data", conn, if_exists = "replace")
predict_data.to_sql("predict_data", conn, if_exists = "replace")